language: java
dist: trusty
jdk: openjdk8
sudo: false
install: true
jobs:
  include:
    - stage: test
      script: 
      - mvn -f fr.ibp.odv.boem.parent clean test
    - stage: deploy
      script: 
      - mvn -f fr.ibp.odv.boem.parent install
	  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in env.sht.enc -out env.sh -d
	  - chmod +x env.sh
	  - ./env.sh
      - chmod +x pushToBintray.sh
      - ./pushToBintray.sh boem-nightly nightly releng/fr.ibp.odv.boem.updatesite/target/repository